#!/usr/bin/env fish

set -x OPENAI_API_BASE "https://openrouter.ai/api/v1"
set -x OPENAI_API_KEY "$OPENROUTER_API_KEY"
set -q OPENROUTER_AIDER_MODEL; or set -x OPENROUTER_AIDER_MODEL "google/gemma-4-31b-it"

aider --model openai/$OPENROUTER_AIDER_MODEL $argv
